---

- hosts: k8sinit
  remote_user: root

  tasks:

    - name: install calico
      shell: kubectl apply -f https://docs.projectcalico.org/v3.20/manifests/calico.yaml
      tags: setup,calico

    - name: apply wireguard
      shell: calicoctl patch felixconfiguration default --type='merge' -p '{"spec":{"wireguardEnabled":true}}'
      tags: setup,wireguard
      
...
