---

- hosts: k8sadds
  remote_user: root
  vars_files:
    - /var/lib/jenkins/adds.yml

  tasks:

    - name: aptitude update
      shell: aptitude update -y && aptitude upgrade -y && aptitude install apt-transport-https curl gnupg2 -y
      tags: setup

    - name: install docker.io
      shell: aptitude install docker.io -y
      tags: setup

    - name: dat br_netfilter module k
      shell: lsmod | grep br_netfilter || modprobe br_netfilter
      tags: setup

    - name: setup the apt key
      shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      tags: setup
      command_warning: False

    - name: do the repo add add truncate to this
      shell: echo  "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
      tags: setup

    - name: aptitude update again
      shell: aptitude update -y
      tags: setup

    - name: install kubelet kubeadm and kubectl
      shell: aptitude install kubelet kubeadm kubectl -y
      tags: setup

    - name: swapoff as required for k8s
      shell: swapoff -a && grep -v swap /etc/fstab > /var/tmp/.fstab_tmp && mv /var/tmp/.fstab_tmp /etc/fstab
      tags: setup

    - name: sysctl -p for port forwarding
      shell: sysctl -p
      tags: setup

    - name: join primary
      shell: kubeadm join {{ controlPlanesServer }}:6443 --token {{ token }} --discovery-token-ca-cert-hash {{ caCertHash }}
      tags: join
        
    - name: daemon reload
      shell: systemctl daemon-reload && systemctl restart kubelet.service
      tags: daemon-reload

...
